project:
  title: "Quarto Reporting Template"
  type: default
  output-dir: _output

format:
  html:
    theme: styles/report-html.scss
    css: 
      - styles/fontawesome/css/all.min.css
    toc: false
    page-layout: full
    smooth-scroll: true
    embed-resources: true
    pdf-engine: chromium

  pdf:
    documentclass: article
    geometry: "margin=0.75in"
    keep-tex: false
    toc: false
    number-sections: false
    include-in-header: styles/latex-preamble.tex

params:
  program: "<program>"
  report_date: "2026-01-01"
  period: "quarter"

execute:
  echo: false
  warning: false
  message: false

extensions:
  - shafayetShafee/bsicons
